name: cicd for github actions
on:
 push:
   branches: ["master"]
 pull_request:
      branches: ["master"] 
 workflow_dispatch:
        
jobs:
  test:
     name: run test cases
     runs-on: ubuntu-latest
    #  container:
    #       image: vinod99998888/java-v17.0.9-maven-v3.8.6:latest
     steps:    
        - name: checkout code 
          uses: actions/checkout@v4 

        - name: Set up Java 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '17'  

        - name: Install Maven 3.9.3
          run: |
            MAVEN_VERSION=3.9.3
            curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
            tar -xzf maven.tar.gz
            sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
            echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
            echo "/opt/maven/bin" >> $GITHUB_PATH    

        - name: run unit test cases
          run: |
             java --version && mvn --version
             mvn clean test
             

        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: surefire-reports
            path: target/surefire-reports/*.xml
            retention-days: 1  

  build:
     name: build the maven application
     runs-on: ubuntu-latest
    #  container:
    #     image: vinod99998888/java-v17.0.9-maven-v3.8.6:latest
     needs: test
     steps:
       - name: checkout code 
         uses: actions/checkout@v4  

       - name: Set up Java 17
         uses: actions/setup-java@v3
         with:
            distribution: 'temurin' 
            java-version: '17'  

       - name: Install Maven 3.9.3
         run: |
            MAVEN_VERSION=3.9.3
            curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
            tar -xzf maven.tar.gz
            sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
            echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
            echo "/opt/maven/bin" >> $GITHUB_PATH    
       
       - name: build that application using maven
         run: |
             mvn clean package -DskipTests

       - name: upload artifacts
         uses: actions/upload-artifact@v4
         with:
            name: jar-file
            path: target/my-app-1.0-SNAPSHOT.jar
            retention-days: 1     

  deliver:
     name: run jar file 
     needs:
        - test
        - build
     runs-on: ubuntu-latest
    #  container:
    #       image: vinod99998888/java-v17.0.9-maven-v3.8.6:latest
     steps:    
        - name: checkout code 
          uses: actions/checkout@v4 

        - name: Set up Java 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '17'  

        - name: Download artifacts from test job
          uses: actions/download-artifact@v4
          with: 
             name: surefire-reports

        - name: Download artifacts from build job
          uses: actions/download-artifact@v4
          with: 
             name: jar-file

        - name: execute jar file 
          run: |
             ls -l         
             ./jenkins/scripts/deliver.sh 
              
          
          
       