name: cicd for github actions
on:
 push:
   branches: ["containers"]
 pull_request:
      branches: ["containers"] 
 workflow_dispatch:
        
jobs:
  build:
     name: Build
     needs:
       - test
     runs-on: ubuntu-latest
     container:
        image: vinod99998888/java-v17.0.9-maven-v3.9.3:latest
     steps:
       - name: checkout code 
         uses: actions/checkout@v4  

       - name: build that application using maven
         run: |
             java --version && mvn --version
             mvn clean package -DskipTests

       - name: upload artifacts
         uses: actions/upload-artifact@v4
         with:
            name: jar-file
            path: ./target/my-app-1.0-SNAPSHOT.jar
            retention-days: 1   

  test:
     name: Test
     runs-on: ubuntu-latest
     container:
          image: vinod99998888/java-v17.0.9-maven-v3.9.3:latest
     steps:    
        - name: checkout code 
          uses: actions/checkout@v4 

        - name: run unit test cases
          run: |
             java --version && mvn --version
             mvn clean test

        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: surefire-reports
            path:  target/surefire-reports/*.xml
            retention-days: 1          

  deliver:   # in this stage we will execute our jar file
     name: Deliver
     needs:
        - test
        - build
     runs-on: ubuntu-latest
     container:
        image: vinod99998888/java-v17.0.9-maven-v3.9.3:latest
     steps:
        - name: checkout code 
          uses: actions/checkout@v4 

        - name: Download artifacts from build job   #Download artifacts from build stage
          uses: actions/download-artifact@v4
          with: 
             name: jar-file
             path: ./target

        - name: execute jar file    #Executing jar file it will print Hello World
          run: |
             ls -l         
             sh jenkins/scripts/deliver.sh               
          
          
       