name: cicd for github actions
on:
 push:
   branches: ["master"]
 pull_request:
      branches: ["master"] 
 workflow_dispatch:
        
jobs:
  test:
     name: run test cases
     runs-on: ubuntu-latest
     container:
          image: vinod99998888/java-v17.0.9-maven-v3.8.6:latest
     steps:    
        - uses: actions/checkout@v4 

        - name: run unit test cases
          run: |
             mvn clean test
             ls -l "$GITHUB_WORKSPACE"

  build:
     name: build the maven application
     runs-on: ubuntu-latest
     container:
        image: vinod99998888/java-v17.0.9-maven-v3.8.6:latest
     needs: test
     steps:
       - uses: actions/checkout@v4   
       
       - name: build that maven application
         run: |
             mvn clean package -DskipTests
             ls -l "$GITHUB_WORKSPACE"
          
          
       